name: Build and test
on: [push, pull_request]

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ref: ${{ env.GITHUB_HEAD_REF }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      
      - name: Build using makefile
        run: make

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: linux-aes-finder
          path: ./aes-finder

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ref: ${{ env.GITHUB_HEAD_REF }}

      - name: Install dependencies
        run: |
          brew install openssl

      - name: Build using make
        run: make

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: mac-aes-finder
          path: ./aes-finder

  windows:
    name: Windows
    runs-on: windows-2016
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ref: ${{ env.GITHUB_HEAD_REF }}

      - name: Build
        run: |
          msbuild aes-finder.sln

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: windows-aes-finder
          path: ./aes-finder.exe